name: Generate ASCII Artwork
on:
  push

jobs:
    build-job1:
        runs-on: ubuntu-latest 
        steps:
        - name: install cowsay program
          run: sudo apt-get install cowsay -y
        
        - name: execute cowsay cmd
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" »> dragon.txt grep -i "dragon" dragon.txt
        
        - name: upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: dragon-artifact
            path: dragon.txt


    test-job2:
        needs: [build-job1]
        runs-on: ubuntu-latest 
        steps:
        - name: download artifact
          uses: actions/download-artifact@v3
          with:
            name: dragon-artifact
        
        - name: test file exists
          run: grep -i "dragon" dragon.txt

    deploy-job3:
        needs: [test-job2]
        runs-on: ubuntu-latest 
        steps:
        - name: download artifact
          uses: actions/download-artifact@v3
          with:
            name: dragon-artifact

        - name: read file
          run: cat dragon.txt
        
        - name: deploy 
          run: echo Deploying ... .. .


