name: Generate ASCII Artwork
on:
  push

jobs:
    build-job1:
        runs-on: ubuntu-latest 
        steps:
        - name: install cowsay program
          run: sudo apt-get install cowsay -y
        
        - name: execute cowsay cmd
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" »> dragon.txt grep -i "dragon" dragon.txt

        - name: sleep for 30 seconds
          run: sleep 30

    test-job2:
        needs: [build-job1]
        runs-on: ubuntu-latest 
        steps:
        - name: sleep for 10 seconds
          run: sleep 10
        
        - name: test file exists
          run: grep -i "dragon" dragon.txt

    deploy-job3:
        needs: [test-job2]
        runs-on: ubuntu-latest 
        steps:
        - name: read file
          run: cat dragon.txt
        
        - name: deploy 
          run: echo Deploying ... .. .


